bases:
  - ../../base

namePrefix: dev-

patches:
  - path: service.yaml
    target:
      name: apache-service
      namespace: default
      kind: Service
  
configMapGenerator:
  - name: index-html
    files:
      - index.html


