apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
  labels:
    app: apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache
        image: httpd:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/local/apache2/htdocs
          readOnly: true
          subPath: index.html
          name: apache-conf
      volumes:
        - name: apache-conf
          configMap:
            name: apache-conf
            items:
              - key: index.html
                path: index.html
---
apiVersion: v1
kind: Service
metadata:
  name: apache-service
spec:
  type: NodePort
  selector:
    app: apache
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30087
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: index.html
data:
  index.html: |
    <html><body><h1> DEV </h1></body></html>