apiVersion: v1
kind: Service
metadata:
  name: beetroot-service
spec:
  selector:
    app.kubernetes.io/name: beetrootApp
  clusterIP: 10.106.157.100
  ports:
  - name: beetport
    protocol: TCP
    port: 8080
    targetPort: beetport