apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
  labels:
    app: apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache
        image: httpd:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/local/apache2/conf/httpd.conf
          readOnly: true
          subPath: httpd.conf
          name: httpd-conf
      volumes:
        - name: httpd-conf
          configMap:
            name: httpd-conf
            items:
              - key: httpd.conf
                path: httpd.conf