apiVersion: v1
kind: Pod
metadata:
  name: mysql-pv-pod
spec:
  volumes:
    - name: mysql-pv-storage
      persistentVolumeClaim:
        claimName: mysql-pv-claim
  containers:
    - name: mysql-pv-container
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: mysql-pv-storage
