apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/nginx/conf.d/
          readOnly: true
          name: nginx-conf
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf
            items:
              - key: beetroot.revprox.conf
                path: beetroot.revprox.conf
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-conf
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  beetroot.revprox.conf: |
    server {
    listen 80;
    listen [::]:80;

    server_name www.localhost;

    location / {
      proxy_pass http://10.106.157.89:8080/;
      } 
    }
